Koval_project/app/contact_form/models.py
from .. import db


class Message(db.Model):
    __tablename__ = "messages"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(15), unique=False, nullable=True)
    email = db.Column(db.String(40), unique=False, nullable=True)
    phone = db.Column(db.String(15), unique=False, nullable=True)
    library = db.Column(db.String(15), unique=False, nullable=True)
    message = db.Column(db.Text, unique=False, nullable=True)

    def __repr__(self):
        return f"Name : {self.name}, Email: {self.email}"

Koval_project/app/contact_form/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo, ValidationError


class Myform(FlaskForm):

    name = StringField("Name", validators=[DataRequired(),
                                           Length(min=4, max=10,
                                                  message='Length of this field must be between 4 and 10')])

    email = StringField("Email", validators=[DataRequired(), Email(message='Enter correct email')])

    phone = StringField("Phone", validators=[DataRequired(),
                                             Regexp(regex='^\+380[0-9]{9}', message='Enter correct phone number')])

    library = SelectField("Library", choices=['Numpy', 'Pandas', 'Matplotlib', 'Seaborn'])

    message = TextAreaField("Message", validators=[DataRequired(), Length(max=500,
                                                                          message='Max length of this field is 500')])
    submit = SubmitField("Send")

Koval_project/app/contact_form/__init__.py
from flask import Blueprint

contact_form_bp = Blueprint('contact_form', __name__,
                            template_folder='templates/contact_form')
from . import views

Koval_project/app/contact_form/views.py
from flask import Flask, render_template, request, session, redirect, url_for, flash
from loguru import logger
from .. import db
from .models import Message
from .forms import Myform
from . import contact_form_bp

logger.add("messages.log", format="{time:YYYY-MM-DD HH:mm:ss.SSS} | [{level}] | {message}")


@contact_form_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = Myform()
    if form.validate_on_submit():
        session['username'] = form.name.data
        session['email'] = form.email.data
        save_message_to_db(form)
        flash(f"Your message has been sent: {form.name.data}, {form.email.data}", category='success')
        return redirect(url_for("contact_form.contact"))

    elif request.method == 'POST':
        flash("Post method validation failed", category='warning')
        return render_template('contact.html', form=form)

    form.name.data = session.get("username")
    form.email.data = session.get("email")
    return render_template('contact.html', form=form, username=session.get('username'))


@contact_form_bp.route('/clear')
def clear():
    session.pop('username', default=None)
    session.pop('email', default=None)
    return redirect(url_for("contact_form.contact"))


@contact_form_bp.route('/database')
def database():
    messages = Message.query.all()
    return render_template('database.html', messages=messages)


@contact_form_bp.route('/database/delete/<id>')
def delete_message(id):
    db.session.delete(Message.query.get_or_404(id))
    db.session.commit()
    return redirect(url_for("contact_form.database"))


def save_message_to_db(form):
    logger.success(f"{form.name.data} | {form.email.data} | {form.phone.data} | {form.library.data} | {form.message.data} |")
    session['username'] = form.name.data
    session['email'] = form.email.data

    message = Message(
        name=form.name.data,
        email=form.email.data,
        phone=form.phone.data,
        library=form.library.data,
        message=form.message.data
    )
    try:
        db.session.add(message)
        db.session.commit()
    except:
        db.session.flush()
        db.session.rollback()


Koval_project/app/contact_form/templates/contact_form/contact.html
{% extends "layout.html" %}

{% block body %}

{% from "_render_field.html" import render_field %}

  <div class="col-6 mx-auto">

    <br><br><center><div class="card w-75 text-center">

      <div class="card-header bg-dark">
        <h5 class="text-center" style="color:white">WTF-Form</h5>
      </div>

      <div class="card-body bg-success">
        <form class="text-lite" method="post">
          {{ form.csrf_token }}
          {{ render_field(form.name, class="text-center form-control") }}
          {{ render_field(form.email, class="text-center form-control") }}
          {{ render_field(form.phone, class="text-center form-control") }}
          {{ render_field(form.library, class="text-center form-control") }}
          {{ render_field(form.message, class="text-center form-control") }}
          {{ form.submit(class="btn btn-dark w-100") }}
        </form>
      </div>

    </div>
  </center>
  </div>

{% endblock %}

Koval_project/app/contact_form/templates/contact_form/database.html
{% extends 'layout.html' %}
{% block title %} Database {% endblock %}

{% block name %}
<br><h1 class="text-center">Messages</h1><br>
{% endblock %}

{% block body %}
<table class="table table-hover table-bordered table-striped">
    <thead class="text-center table-primary">
      <tr>
       <th scope="col">Id</th>
       <th scope="col">Name</th>
       <th scope="col">Email</th>
       <th scope="col">Phone</th>
       <th scope="col">Library</th>
       <th scope="col">Message</th>
       <th scope="col">Delete</th>
      </tr>
    </thead>
    {% for data in messages %}
    <tbody>
      <tr class="text-center align-middle">
       <td>{{data.id}}</td>
       <td>{{data.name}}</td>
       <td>{{data.email}}</td>
       <td>{{data.phone}}</td>
       <td>{{data.library}}</td>
       <td>{{data.message}}</td>
       <td><a href="{{ url_for('contact_form.delete_message', id=data.id) }}" type="button" class="btn btn-danger">Delete</a></td>
       </tr>
    </tbody>
    {% endfor%}
 </table>
{% endblock %}